// ----------------------------------------------------------------
// thrift api for watchbase
//
// This is a Thrift interface definition file for the WatchBase service.
// Target language libraries for C++, Java, Ruby, PHP, (and more) are
// generated by running this file through the Thrift compiler with the
// appropriate flags. The Thrift compiler binary and runtime
// libraries for various languages are available
// from the Apache Incubator (http://incubator.apache.org/thrift/)
// ----------------------------------------------------------------

namespace cpp example
struct Metric {
 1: string sn #服务器盘点号
 2: string timestamp #数据收集时间
 3: string name # 监控类型
 4: string value # 监控值
 }
service WatchProxy {
 bool Push(1:Metric metric) # 监控数据，返回存储结果值。
}
